### ISSUE TITLE
All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.TransportException: [/127.0.0.1:9042] Cannot connect)) 

### ISSUE THREAD

**Issue by xyy9949** [burcuku/explorer-server#4]
Hello, I followed the guidance you gave and successfully built the test-server and cas-6023. I also modified the paths of directories and binaries. However, I could not run the test. The error message shows below.
I'm looking forward to your solution! Thank you!

5711 [main] WARN explorer.workload.CassWorkload - === Error with communication to node 0
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.TransportException: [/127.0.0.1:9042] Cannot connect))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1455)
at com.datastax.driver.core.Cluster.init(Cluster.java:158)
at explorer.workload.CassWorkload.executeCql(CassWorkload.java:72)
at explorer.workload.CassWorkload.execute6023(CassWorkload.java:24)
at explorer.workload.CassWorkloadDriver.sendWorkload(CassWorkloadDriver.java:63)
at explorer.SystemRunner.runAll(SystemRunner.java:123)
at explorer.SystemRunner.runAll(SystemRunner.java:76)
at explorer.SystemRunner.main(SystemRunner.java:45)
11270 [main] WARN explorer.workload.CassWorkload - === Error with communication to node 1
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.2:9042 (com.datastax.driver.core.TransportException: [/127.0.0.2:9042] Cannot connect))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1455)
at com.datastax.driver.core.Cluster.init(Cluster.java:158)
at explorer.workload.CassWorkload.executeCql(CassWorkload.java:72)
at explorer.workload.CassWorkload.execute6023(CassWorkload.java:28)
at explorer.workload.CassWorkloadDriver.sendWorkload(CassWorkloadDriver.java:63)
at explorer.SystemRunner.runAll(SystemRunner.java:123)
at explorer.SystemRunner.runAll(SystemRunner.java:76)
at explorer.SystemRunner.main(SystemRunner.java:45)
^CException in thread "Thread-1" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.TransportException: [/127.0.0.1:9042] Cannot connect))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1455)
at com.datastax.driver.core.Cluster.init(Cluster.java:158)
at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:329)
at com.datastax.driver.core.Cluster.connect(Cluster.java:279)
at explorer.verifier.CassVerifier.getValues(CassVerifier.java:48)
at explorer.verifier.CassVerifier.checkDataConsistency(CassVerifier.java:20)
at explorer.verifier.CassVerifier.verify(CassVerifier.java:16)
at explorer.SystemRunner.lambda$runAll$0(SystemRunner.java:103)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by burcuku** [comment]
Hello, do you run the program on a Mac? It runs without any problems in Ubuntu but can have issues connecting to the addresses in Mac. 

Could you try running the command below before running the servers?

```
sudo ifconfig lo0 alias 127.0.0.2 255.255.255.0
sudo ifconfig lo0 alias 127.0.0.3 255.255.255.0
```

Hope that helps!
